# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\bugra\Documents\GitHub\x\.qt_for_python\PodcastVideoPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PodcastVideoPlayer(object):
    def setupUi(self, PodcastVideoPlayer):
        PodcastVideoPlayer.setObjectName("PodcastVideoPlayer")
        PodcastVideoPlayer.resize(565, 459)
        PodcastVideoPlayer.setMinimumSize(QtCore.QSize(565, 459))
        PodcastVideoPlayer.setMaximumSize(QtCore.QSize(565, 459))
        PodcastVideoPlayer.setStyleSheet("QLabel\n"
"{\n"
"    color: red;\n"
"    font: 12pt \"Roboto\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(PodcastVideoPlayer)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 641, 481))
        self.tabWidget.setMinimumSize(QtCore.QSize(641, 481))
        self.tabWidget.setMaximumSize(QtCore.QSize(641, 481))
        self.tabWidget.setStyleSheet("QTabBar::tab:selected, QTabBar::tab:!selected:hover\n"
"{\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"    border-bottom: 3px;\n"
"    border-bottom-style: solid;\n"
"    border-bottom-color: rgb(172, 172, 172);\n"
"    background-color: red;\n"
"    color: white;\n"
"    margin-right: 6px;\n"
"    margin-left: 2px;\n"
"    padding-right: 6px;\n"
"    padding-left: 9px;\n"
"    padding-bottom: 2px;\n"
"    font-size: 11px;\n"
"    border-top-left-radius: 9px;\n"
"    border-top-right-radius: 9px;\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    border: 1px solid black;\n"
"    border-radius: 9px;\n"
"    color: red;\n"
"    padding-left: 19px;\n"
"    padding-right: 19px;\n"
"}\n"
"\n"
"QTabWidget::pane \n"
"{\n"
"    border-top: 2px solid #C2C7CB;\n"
"    position: absolute;\n"
"    top: 5.5px;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tabSaveVideo = QtWidgets.QWidget()
        self.tabSaveVideo.setObjectName("tabSaveVideo")
        self.widget = QtWidgets.QWidget(self.tabSaveVideo)
        self.widget.setGeometry(QtCore.QRect(0, 0, 641, 451))
        self.widget.setObjectName("widget")
        self.lblVideoLink = QtWidgets.QLabel(self.widget)
        self.lblVideoLink.setGeometry(QtCore.QRect(30, 150, 71, 20))
        self.lblVideoLink.setObjectName("lblVideoLink")
        self.lneVideoLink = QtWidgets.QLineEdit(self.widget)
        self.lneVideoLink.setGeometry(QtCore.QRect(30, 190, 371, 31))
        self.lneVideoLink.setStyleSheet("#lneVideoLink\n"
"{\n"
"    border-top: none;\n"
"    border-right: none;\n"
"    border-left: none;\n"
"    border-bottom: 2px solid black;\n"
"    background-color: transparent;\n"
"    color: red;\n"
"    font: 11pt \"Roboto\";\n"
"}\n"
"\n"
"#lineEdit::placeholder\n"
"{\n"
"    color: transparent;\n"
"}")
        self.lneVideoLink.setObjectName("lneVideoLink")
        self.btnSave = QtWidgets.QPushButton(self.widget)
        self.btnSave.setGeometry(QtCore.QRect(410, 190, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btnSave.setFont(font)
        self.btnSave.setStyleSheet("QPushButton\n"
"{\n"
"    border: none;\n"
"    background-color: red;\n"
"    color: white;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(141, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(191, 0, 0);\n"
"}\n"
"")
        self.btnSave.setObjectName("btnSave")
        self.tabWidget.addTab(self.tabSaveVideo, "")
        self.tabSeeVideo = QtWidgets.QWidget()
        self.tabSeeVideo.setObjectName("tabSeeVideo")
        self.widget_2 = QtWidgets.QWidget(self.tabSeeVideo)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 641, 451))
        self.widget_2.setObjectName("widget_2")
        self.lstSavedVideos = QtWidgets.QListWidget(self.widget_2)
        self.lstSavedVideos.setGeometry(QtCore.QRect(5, 40, 271, 391))
        self.lstSavedVideos.setStyleSheet("QListWidget\n"
"{\n"
"    color: red;\n"
"    font: 12pt \"Roboto\";\n"
"}\n"
"\n"
"QListWidget::item:selected, QListWidget::item:!selected:hover\n"
"{\n"
"    background-color: red;\n"
"    border: none;\n"
"    color: white;\n"
"}")
        self.lstSavedVideos.setObjectName("lstSavedVideos")
        self.lblSavedVideos = QtWidgets.QLabel(self.widget_2)
        self.lblSavedVideos.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.lblSavedVideos.setObjectName("lblSavedVideos")
        self.chkDownloadAllOfVideos = QtWidgets.QCheckBox(self.widget_2)
        self.chkDownloadAllOfVideos.setGeometry(QtCore.QRect(290, 180, 271, 20))
        self.chkDownloadAllOfVideos.setStyleSheet("QCheckBox\n"
"{\n"
"    \n"
"    font: 12pt \"Roboto\";\n"
"}\n"
"\n"
"QCheckBox:checked\n"
"{\n"
"    color: red;\n"
"}\n"
"\n"
"QCheckBox::indicator:pressed\n"
"{\n"
"    background-color: red;\n"
"}")
        self.chkDownloadAllOfVideos.setObjectName("chkDownloadAllOfVideos")
        self.btnDownloadVideo = QtWidgets.QPushButton(self.widget_2)
        self.btnDownloadVideo.setGeometry(QtCore.QRect(290, 140, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btnDownloadVideo.setFont(font)
        self.btnDownloadVideo.setStyleSheet("QPushButton\n"
"{\n"
"    border: none;\n"
"    background-color: red;\n"
"    color: white;\n"
"    font-weight: 400;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(141, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(191, 0, 0);\n"
"}\n"
"")
        self.btnDownloadVideo.setObjectName("btnDownloadVideo")
        self.chkPlayAllOfVideos = QtWidgets.QCheckBox(self.widget_2)
        self.chkPlayAllOfVideos.setGeometry(QtCore.QRect(290, 100, 231, 20))
        self.chkPlayAllOfVideos.setStyleSheet("QCheckBox\n"
"{\n"
"    \n"
"    font: 12pt \"Roboto\";\n"
"}\n"
"\n"
"QCheckBox:checked\n"
"{\n"
"    color: red;\n"
"}\n"
"\n"
"QCheckBox::indicator:pressed\n"
"{\n"
"    background-color: red;\n"
"}")
        self.chkPlayAllOfVideos.setObjectName("chkPlayAllOfVideos")
        self.btnPlayVideo = QtWidgets.QPushButton(self.widget_2)
        self.btnPlayVideo.setGeometry(QtCore.QRect(290, 60, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btnPlayVideo.setFont(font)
        self.btnPlayVideo.setStyleSheet("QPushButton\n"
"{\n"
"    border: none;\n"
"    background-color: red;\n"
"    color: white;\n"
"    font-weight: 400;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(141, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(191, 0, 0);\n"
"}\n"
"")
        self.btnPlayVideo.setObjectName("btnPlayVideo")
        self.lblPlayingVideo = QtWidgets.QLabel(self.widget_2)
        self.lblPlayingVideo.setGeometry(QtCore.QRect(290, 310, 171, 21))
        self.lblPlayingVideo.setObjectName("lblPlayingVideo")
        self.lblVideoName = QtWidgets.QLabel(self.widget_2)
        self.lblVideoName.setGeometry(QtCore.QRect(290, 340, 271, 21))
        self.lblVideoName.setText("")
        self.lblVideoName.setObjectName("lblVideoName")
        self.chkSetQuality = QtWidgets.QCheckBox(self.widget_2)
        self.chkSetQuality.setGeometry(QtCore.QRect(290, 210, 101, 20))
        self.chkSetQuality.setStyleSheet("QCheckBox\n"
"{\n"
"    \n"
"    font: 12pt \"Roboto\";\n"
"}\n"
"\n"
"QCheckBox:checked\n"
"{\n"
"    color: red;\n"
"}\n"
"\n"
"QCheckBox::indicator:pressed\n"
"{\n"
"    background-color: red;\n"
"}")
        self.chkSetQuality.setObjectName("chkSetQuality")
        self.cmbQualities = QtWidgets.QComboBox(self.widget_2)
        self.cmbQualities.setGeometry(QtCore.QRect(400, 210, 131, 22))
        self.cmbQualities.setStyleSheet("QComboBox\n"
"{\n"
"    font: 12pt \"Roboto\";\n"
"    padding: 1px 8px 1px 3px;\n"
"    color: red;\n"
"    border: 0.5px solid black;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"    background-color: red;\n"
"    color: white;\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox  QListView\n"
"{\n"
"    color: red;\n"
"}\n"
"\n"
"")
        self.cmbQualities.setObjectName("cmbQualities")
        self.cmbQualities.addItem("")
        self.cmbQualities.addItem("")
        self.cmbQualities.addItem("")
        self.cmbQualities.addItem("")
        self.btnDeleteVideo = QtWidgets.QPushButton(self.widget_2)
        self.btnDeleteVideo.setGeometry(QtCore.QRect(380, 390, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.btnDeleteVideo.setFont(font)
        self.btnDeleteVideo.setStyleSheet("QPushButton\n"
"{\n"
"    border: none;\n"
"    background-color: red;\n"
"    color: white;\n"
"    font-weight: 400;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(141, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(191, 0, 0);\n"
"}\n"
"")
        self.btnDeleteVideo.setObjectName("btnDeleteVideo")
        self.lblChannelName = QtWidgets.QLabel(self.widget_2)
        self.lblChannelName.setGeometry(QtCore.QRect(290, 260, 271, 21))
        self.lblChannelName.setText("")
        self.lblChannelName.setObjectName("lblChannelName")
        self.lblAuthorName = QtWidgets.QLabel(self.widget_2)
        self.lblAuthorName.setGeometry(QtCore.QRect(290, 235, 171, 21))
        self.lblAuthorName.setObjectName("lblAuthorName")
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setGeometry(QtCore.QRect(276, 290, 311, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.widget_2)
        self.line_2.setGeometry(QtCore.QRect(276, 26, 311, 31))
        self.line_2.setStyleSheet("padding-left: 15px;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget.addTab(self.tabSeeVideo, "")
        PodcastVideoPlayer.setCentralWidget(self.centralwidget)

        self.retranslateUi(PodcastVideoPlayer)
        self.tabWidget.setCurrentIndex(1)
        self.cmbQualities.setVisible(False)
        self.lblAuthorName.setVisible(False)
        self.lblPlayingVideo.setVisible(False)
        self.chkSetQuality.clicked['bool'].connect(self.cmbQualities.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PodcastVideoPlayer)

    def retranslateUi(self, PodcastVideoPlayer):
        _translate = QtCore.QCoreApplication.translate
        PodcastVideoPlayer.setWindowTitle(_translate("PodcastVideoPlayer", "YouTube Podcast & Video Player"))
        self.lblVideoLink.setText(_translate("PodcastVideoPlayer", "Video:"))
        self.lneVideoLink.setPlaceholderText(_translate("PodcastVideoPlayer", "Link of the Video"))
        self.btnSave.setText(_translate("PodcastVideoPlayer", "SAVE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSaveVideo), _translate("PodcastVideoPlayer", "Save a Video"))
        self.lblSavedVideos.setText(_translate("PodcastVideoPlayer", "Saved videos:"))
        self.chkDownloadAllOfVideos.setText(_translate("PodcastVideoPlayer", "Download all of the video in the list"))
        self.btnDownloadVideo.setText(_translate("PodcastVideoPlayer", "Download selected video"))
        self.chkPlayAllOfVideos.setText(_translate("PodcastVideoPlayer", "Play all of the video in the list"))
        self.btnPlayVideo.setText(_translate("PodcastVideoPlayer", "Play selected video"))
        self.lblPlayingVideo.setText(_translate("PodcastVideoPlayer", "Video currently playing:"))
        self.chkSetQuality.setText(_translate("PodcastVideoPlayer", "Set Quality"))
        self.cmbQualities.setItemText(0, _translate("PodcastVideoPlayer", "1080p"))
        self.cmbQualities.setItemText(1, _translate("PodcastVideoPlayer", "720p"))
        self.cmbQualities.setItemText(2, _translate("PodcastVideoPlayer", "480p"))
        self.cmbQualities.setItemText(3, _translate("PodcastVideoPlayer", "360p"))
        self.btnDeleteVideo.setText(_translate("PodcastVideoPlayer", "Delete selected video"))
        self.lblAuthorName.setText(_translate("PodcastVideoPlayer", "Channel name:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSeeVideo), _translate("PodcastVideoPlayer", "See saved videos"))
